[package]
name = "sparsnas"
version = "0.1.0"
authors = ["Daniel Svensson"]

[dependencies]
cc1101 = { git = "https://github.com/dsvensson/cc1101", rev = "master" }
# cc1101 = { path = "../cc1101" }
linux-embedded-hal = "0.2.0"
byteorder = "1.2.2"
hex = "0.3.2"
